name: Auto Commit
on:
  schedule:
    - cron: '40 16 * * 1-6'
  workflow_dispatch:

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Commit and push
        run: |
          git config --global user.name "mxmxmmgg"
          git config --global user.email "mxmxmmgg25"
          git commit --allow-empty -m "Auto-commit: $(date '+%Y-%m-%d')"
          git push
